name: "Setup Node Environment"
description: "Sets up Node.js and installs dependencies"

inputs:
  node-version:
    description: "Node version"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - run: npm ci
      shell: bash
